apiVersion: v1
kind: Service
metadata:
  name: category-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: category-service
  ports:
    - port: 80
      targetPort: 3003
      nodePort: 30080