apiVersion: apps/v1
kind: Deployment
metadata:
  name: attentionlist-browsinghistory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attentionlist-browsinghistory-service
  template:
    metadata:
      labels:
        app: attentionlist-browsinghistory-service
    spec:
      containers:
      - name: attentionlist-browsinghistory-service
        image: carlos8881/attentionlist-browsinghistory-service:latest
        ports:
        - containerPort: 3001