apiVersion: v1
kind: Service
metadata:
  name: attentionlist-browsinghistory-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: attentionlist-browsinghistory-service