apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: category-service
  template:
    metadata:
      labels:
        app: category-service
    spec:
      containers:
      - name: category-service
        image: carlos8881/category-service:latest
        ports:
        - containerPort: 3004